export const FORGOTTEN_FAVORITES_MONTHS = 6;

export const MUSIC_TASTE_PROFILE_TOP_GENRES_COUNT = 5;
export const MUSIC_TASTE_PROFILE_OLDEST_NEWEST_COUNT = 1;
export const MUSIC_TASTE_PROFILE_SPECIALIST_RATIO_THRESHOLD = 0.5;
export const MUSIC_TASTE_PROFILE_DIVERSITY_UNIQUE_ARTISTS = 50;
export const MUSIC_TASTE_PROFILE_TIME_TRAVELER_UNIQUE_DECADES = 5;
export const MUSIC_TASTE_PROFILE_SCORE_MULTIPLIER = 100;
export const MUSIC_TASTE_PROFILE_TOP_DECADE_ARTISTS_COUNT = 10;
